-- Create table for daily subway traffic
create table if not exists subway_traffic (
  id bigint generated by default as identity primary key,
  date date not null,
  station_name text not null,
  line_number text not null,
  boarding_count int,
  alighting_count int,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  
  -- Prevent duplicate entries for the same date/station/line
  unique(date, station_name, line_number)
);

-- Create table for real-time weather data
create table if not exists weather_data (
  id bigint generated by default as identity primary key,
  measured_at timestamp with time zone not null,
  temperature float,
  precipitation_type int,
  humidity float,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
