import os
import requests
from supabase import create_client, Client
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Supabase Configuration
url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_KEY")

if not url or not key:
    raise ValueError("SUPABASE_URL and SUPABASE_KEY must be set in .env")

supabase: Client = create_client(url, key)

def create_tables_if_not_exists():
    """
    Note: Supabase (PostgreSQL) tables are usually created via SQL Editor or Migrations.
    This function documents the expected schema.
    
    -- Table: subway_traffic
    create table if not exists subway_traffic (
        id bigint generated by default as identity primary key,
        date date not null,
        station_name text not null,
        line_number text not null,
        boarding_count int,
        alighting_count int,
        created_at timestamp with time zone default timezone('utc'::text, now())
    );

    -- Table: weather_data
    create table if not exists weather_data (
        id bigint generated by default as identity primary key,
        measured_at timestamp with time zone not null,
        temperature float,
        precipitation_type int,
        humidity float,
        created_at timestamp with time zone default timezone('utc'::text, now())
    );
    """
    print("Ensure tables 'subway_traffic' and 'weather_data' exist in Supabase.")

def insert_subway_data(date, station, line, board, alight):
    """
    Inserts a record into 'subway_traffic' table.
    """
    data = {
        "date": date,  # Format: "YYYY-MM-DD"
        "station_name": station,
        "line_number": line,
        "boarding_count": board,
        "alighting_count": alight
    }
    
    try:
        response = supabase.table("subway_traffic").insert(data).execute()
        print(f"Successfully inserted subway data for {date}")
        return response
    except Exception as e:
        print(f"Error inserting subway data: {e}")

def insert_weather_data(measured_at, temp, rain_type, humidity):
    """
    Inserts a record into 'weather_data' table.
    """
    data = {
        "measured_at": measured_at, # ISO 8601 Format
        "temperature": temp,
        "precipitation_type": rain_type,
        "humidity": humidity
    }
    
    try:
        response = supabase.table("weather_data").insert(data).execute()
        print(f"Successfully inserted weather data for {measured_at}")
        return response
    except Exception as e:
        print(f"Error inserting weather data: {e}")

if __name__ == "__main__":
    create_tables_if_not_exists()
    
    # Example Usage
    # insert_subway_data("2023-10-27", "성수", "2호선", 15000, 14500)
    # insert_weather_data("2023-10-27T14:00:00Z", 22.5, 0, 45.0)
